Web/lampisite/lampi/urls.py
from django.urls import path, re_path

from . import views

app_name = 'lampi'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.AddLampiView.as_view(), name='add'),
    re_path(r'^device/(?P<device_id>[0-9a-fA-F]+)$',
            views.DetailView.as_view(), name='detail'),
    re_path(r'^device/media/(?P<device_id>[0-9a-fA-F]+)$',
            views.MediaView.as_view(), name='media'),
]

Web/lampisite/lampi/models.py
from django.db import models
from django.contrib.auth.models import User
from uuid import uuid4
import json
import paho.mqtt.publish

# Create your models here.
DEFAULT_USER = 'parked_device_user'


def get_parked_user():
    return get_user_model().objects.get_or_create(username=DEFAULT_USER)[0]


def generate_association_code():
    return uuid4().hex


class Lampi(models.Model):
    name = models.CharField(max_length=50, default="My LAMPI")
    device_id = models.CharField(max_length=12, primary_key=True)
    user = models.ForeignKey(User,
                             on_delete=models.SET(get_parked_user))
    association_code = models.CharField(max_length=32, unique=True,
                                        default=generate_association_code)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}: {}".format(self.device_id, self.name)

    def _generate_device_association_topic(self):
        return 'devices/{}/lamp/associated'.format(self.device_id)

    def publish_unassociated_msg(self):
        # send association MQTT message
        assoc_msg = {}
        assoc_msg['associated'] = False
        assoc_msg['code'] = self.association_code
        paho.mqtt.publish.single(
            self._generate_device_association_topic(),
            json.dumps(assoc_msg),
            qos=2,
            retain=True,
            hostname="localhost",
            port=50001,
            )

    def associate_and_publish_associated_msg(self,  user):
        # update Lampi instance with new user
        self.user = user
        self.save()
        # publish associated message
        assoc_msg = {}
        assoc_msg['associated'] = True
        paho.mqtt.publish.single(
            self._generate_device_association_topic(),
            json.dumps(assoc_msg),
            qos=2,
            retain=True,
            hostname="localhost",
            port=50001,
            )

Web/lampisite/lampi/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.conf import settings
from .models import Lampi


def device_association_topic(device_id):
    return 'devices/{}/lamp/associated'.format(device_id)


class AddLampiForm(forms.Form):
    association_code = forms.CharField(label="Association Code", min_length=6,
                                       max_length=6)

    def clean(self):
        cleaned_data = super(AddLampiForm, self).clean()
        print("received form with code {}".format(
              cleaned_data['association_code']))
        # look up device with start of association_code
        uname = settings.DEFAULT_USER
        parked_user = get_user_model().objects.get(username=uname)
        devices = Lampi.objects.filter(
            user=parked_user,
            association_code__startswith=cleaned_data['association_code'])
        if not devices:
            self.add_error('association_code',
                           ValidationError("Invalid Association Code",
                                           code='invalid'))
        else:
            cleaned_data['device'] = devices[0]
        return cleaned_data

Web/lampisite/lampi/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from .models import Lampi
from lampi.forms import AddLampiForm


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'lampi/index.html'

    def get_queryset(self):
        results = Lampi.objects.filter(user=self.request.user)
        print("RESULTS: {}".format(results))
        return results


class DetailView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'lampi/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['device'] = get_object_or_404(
            Lampi, pk=kwargs['device_id'], user=self.request.user)
        print("CONTEXT: {}".format(context))
        return context

class MediaView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'lampi/media.html'

    def get_context_data(self, **kwargs):
        context = super(MediaView, self).get_context_data(**kwargs)
        context['device'] = get_object_or_404(
            Lampi, pk=kwargs['device_id'], user=self.request.user)
        print("CONTEXT: {}".format(context))
        return context

class AddLampiView(LoginRequiredMixin, generic.FormView):
    template_name = 'lampi/addlampi.html'
    form_class = AddLampiForm
    success_url = '/lampi'

    def form_valid(self, form):
        device = form.cleaned_data['device']
        device.associate_and_publish_associated_msg(self.request.user)
        return super(AddLampiView, self).form_valid(form)

Web/lampisite/lampi/templates/lampi/addlampi.html
{% extends "lampi/base.html" %}
{% load static %}
{% block title %}Add LAMPI{% endblock %}

{% block additional_head_content %}
    <link rel="stylesheet" type="text/css" href="{% static 'lampi/css/site.css' %}"/>
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add LAMPI" />
</form>
{% endblock %}

Web/lampisite/lampi/templates/lampi/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}LAMPI{% endblock %}</title>

  <meta charset="utf-8">
  <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">

    {% block additional_head_content %}
    {% endblock %}

</head>
<body>
    <div id="outer-pane" class="centered-root">
         <div>
            {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>
            {% if user.is_superuser %}
                <a href="{% url 'admin:index' %}">Admin</a>
            {% endif %}
            {% else %}
            <a href="{% url 'login' %}">Login</a>
            {% endif %}
            {% block links %}
            {% endblock %}
        </div>
        {% block content %}
        <p>Content Goes Here.</p>
        {% endblock %}
    </div>
</body>
</html>

Web/lampisite/lampi/templates/lampi/detail.html
{% extends "lampi/base.html" %}
{% load static %}

{% block title %}LAMPI{% endblock %}

{% block additional_head_content %}
  <meta name="description" content="LAMPI Control for {{ device.device_id }}">
  <link rel="stylesheet" type="text/css"
         href="{% static 'lampi/css/lampi-sliders.css' %}">


  <style id="saturation-slider-style" type="text/css"></style>
  <style id="hue-thumb-style" type="text/css"></style>
  <style id="brightness-thumb-style" type="text/css"></style>
  <style id="saturation-thumb-style" type="text/css"></style>
{% endblock %}

{% block content %}
    <script type="text/javascript">
        var window_global = {};
        window_global['device_id'] = "{{ device.device_id }}";
        window_global['mqtt'] = {'hostname': window.location.hostname,
                                'websockets_port': 50002};
    </script>
		<div id="top-pane">
			<div id="sliders">
				<input id="hue-slider" class="hue slider" type="range" min="0.0" max="1.0" step="0.01"></input>
				<input id="saturation-slider" class="saturation slider" type="range" min="0.0" max="1.0" step="0.01"></input>
				<input id="brightness-slider" class="brightness slider" type="range" min="0.0" max="1.0" step="0.01"></input>
			</div>
		</div>
		<div id="colorbox"></div>
		<div id="bottom-pane">
			<div class="toggle-button" id="power"></div>
		</div>
	</div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.2/mqttws31.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js" type="text/javascript"></script>

    <script src="{% static 'lampi/js/tinycolor.js' %}" type="text/javascript"></script>
    <script src="{% static 'lampi/js/lampi.js' %}" type="text/javascript"></script>
    <script src="{% static 'lampi/js/lampi-sliders.js' %}" type="text/javascript"></script>

{% endblock %}

{% block page_event %}LAMPI Detail{% endblock %}

Web/lampisite/lampi/templates/lampi/index.html
{% extends "lampi/base.html" %}
{% load static %}

{% block additional_head_content %}
<link rel="stylesheet" type="text/css" href="{% static 'lampi/css/site.css' %}"/>
{% endblock %}

{% block content %}

{% if lampi_list %}
    <ul>
    {% for device in lampi_list %}
       <li><a href="{% url 'lampi:detail' device.device_id %}">
        {{ device.name }} {{device.device_id }}</a></li>
    {% endfor %}
    </ul>
    <a href="{% url 'lampi:add' %}">Add a LAMPI Device</a>
{% else %}
    <p>No devices are available.</p>
    <a href="{% url 'lampi:add' %}">Add a LAMPI Device</a>
{% endif %}

{% endblock %}

Web/lampisite/lampi/templates/lampi/login.html
{% extends "lampi/base.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block additional_head_content %}
  <link rel="stylesheet" type="text/css" href="{% static 'lampi/css/site.css' %}"/>
{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

Web/lampisite/lampi/templates/lampi/logout.html
{% extends "lampi/base.html" %}
{% load static %}

{% block title %}Logged Out{% endblock %}

{% block additional_head_content %}
  <link rel="stylesheet" type="text/css" href="{% static 'lampi/css/site.css' %}"/>
{% endblock %}  
{% block content %}
  <p>Logged out</p>
{% endblock %}

Web/lampisite/lampi/templates/lampi/media.html
{% extends "lampi/base.html" %}
{% load static %}

{% block title %}LAMPI{% endblock %}

{% block additional_head_content %}
<style>
  .frame {
    width: 50%;
    border: 3px solid #ccc;
    background: #eee;
    margin: auto;
    padding: 15px 10px;
  }

  img {
    width: 100%;
    height: 100%;
  }

  body {background-color: burlywood;}

  .content {
    width: 70%; /* Could be anything, but 75% works here. */
    margin: auto;
 }
 a, h1, h2, label, p {
    color: white;
    text-align:center;
}
</style>
{% endblock %}

{% block links %}
<a href="{% url 'lampi:detail' device.device_id %}">Lighting</a>
<a href="{% url 'lampi:media' device.device_id %}">Media</a>
{% endblock %}

{% block content %}
<div class="content">
<h1> Smart Frame Media Control </h1>
<script type="text/javascript">
  var window_global = {};
  window_global['device_id'] = "{{ device.device_id }}";
  window_global['mqtt'] = {
    'hostname': window.location.hostname,
    'websockets_port': 50002
  };
</script>

<div>
  <h2>Current Media</h2>
  <div class="frame">
    <img id="cur_media" src="https://res.cloudinary.com/thai-cloudinary/image/upload/v1649884273/panda_opfuus.jpg">
  </div>
  <h2>Upload New Media</h2>
  <script src="https://upload-widget.cloudinary.com/global/all.js" type="text/javascript"></script>
  <button id="upload_widget" class="cloudinary-button" style="display:block; margin: 0 auto;">Upload files</button>
  <script type="text/javascript">
    var myWidget = cloudinary.createUploadWidget({
      cloudName: 'thai-cloudinary',
      showAdvancedOptions: true,
      uploadPreset: 'smart_frame_upload',
      sources: ["local", "url"],
      theme: 'purple',
      fonts: {
        "'Cute Font', cursive": "https://fonts.googleapis.com/css?family=Cute+Font",
      },
      text: {
        "en": {
            "queue": {
                "title": "Files to upload",
                "title_uploading_with_counter": "Uploading image to cloud ..."
            },
            "advanced": "Add message",
            "advanced_options": {
                "public_id_ph": "Message to send with upload",
                "tags_ph": "Add a tag",
                "add_new": "Add a new tag:",
                "upload_preset_placeholder": "Upload Preset"
            },
        }
      }

    }, (error, result) => {
      if (!error && result && result.event === "success") {
        console.log('Done! Here is the image info: ', result.info);
        update_media(result.info)
      }
    }
    )

    document.getElementById("upload_widget").addEventListener("click", function () {
      myWidget.open();
    }, false);
  </script>
</div>
</div>

</div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.2/mqttws31.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js"
  type="text/javascript"></script>

<script src="{% static 'lampi/js/tinycolor.js' %}" type="text/javascript"></script>
<script src="{% static 'lampi/js/lampi.js' %}" type="text/javascript"></script>
<script src="{% static 'lampi/js/lampi-sliders.js' %}" type="text/javascript"></script>

{% endblock %}